### ISSUE TITLE
`micropip.install('bw2XXX')` Errors

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-hub#30]
Tested in [the Pyodide 0.24.0 REPL](https://pyodide.org/en/stable/console.html):

 - [x] `bw2calc==2.0.dev14` 🎉
 - [x] `bw2io==0.9.dev21` 🤨

```
ValueError: Can't find a pure Python 3 wheel for: 'docopt', 'unicodecsv', 'ps
util'
```

...magically worked the second time?!

 - [x] `bw2data==4.0.dev25` 🎉

<details>
  <summary>To Reproduce...</summary>
```
>>> await micropip.install('bw2io==0.9.dev21')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 138, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 204, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 319, in add_requirement_inner
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 357, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 201, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 319, in add_requirement_inner
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 357, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 197, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 201, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 304, in add_requirement_inner
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/micropip/transaction.py", line 403, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'docopt'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
>>> await micropip.install('bw2io==0.9.dev21', keep_going = True)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.11/site-packages/micropip/_commands/install.py", line 142, in install
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for: 'docopt', 'unicodecsv', 'psutil'
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
>>> micropip.list()
Name      | Version | Source
--------- | ------- | -------
packaging | 23.1    | pyodide
micropip  | 0.4.0   | pyodide
>>> await micropip.install('bw2calc==2.0.dev14', keep_going = True)
>>> micropip.list()
Name            | Version   | Source
--------------- | --------- | -------
packaging       | 23.1      | pyodide
micropip        | 0.4.0     | pyodide
stats-arrays    | 0.6.5     | pypi
appdirs         | 1.4.4     | pypi
fs              | 2.4.16    | pypi
bw-processing   | 0.8.5     | pypi
matrix-utils    | 0.2.5     | pypi
bw2calc         | 2.0.dev14 | pypi
six             | 1.16.0    | pyodide
numpy           | 1.25.2    | pyodide
python-dateutil | 2.8.2     | pyodide
pytz            | 2023.3    | pyodide
pandas          | 1.5.3     | pyodide
pyparsing       | 3.1.1     | pyodide
setuptools      | 68.1.2    | pyodide
scipy           | 1.11.1    | pyodide
distutils       | 1.0.0     | pyodide
openblas        | 0.3.23    | pyodide
>>> await micropip.install('bw2data==4.0.dev25', keep_going = True)
>>> micropip.list()
Name              | Version   | Source
----------------- | --------- | -------
packaging         | 23.1      | pyodide
micropip          | 0.4.0     | pyodide
stats-arrays      | 0.6.5     | pypi
appdirs           | 1.4.4     | pypi
fs                | 2.4.16    | pypi
bw-processing     | 0.8.5     | pypi
matrix-utils      | 0.2.5     | pypi
bw2calc           | 2.0.dev14 | pypi
six               | 1.16.0    | pyodide
numpy             | 1.25.2    | pyodide
python-dateutil   | 2.8.2     | pyodide
<long output truncated>
        | 0.22      | pypi
bw2parameters     | 1.1.0     | pypi
bw2data           | 4.0.dev25 | pypi
tqdm              | 4.66.1    | pyodide
wrapt             | 1.15.0    | pyodide
lxml              | 4.9.3     | pyodide
pycparser         | 2.21      | pyodide
typing_extensions | 4.7.1     | pyodide
cffi              | 1.15.1    | pyodide
peewee            | 3.16.3    | pyodide
distutils         | 1.0.0     | pyodide
openblas          | 0.3.23    | pyodide
sqlite3           | 1.0.0     | pyodide
>>> await micropip.install('bw2io==0.9.dev21', keep_going = True)
>>> import bw2io
>>> import bw2data
>>> import bw2calc
```
</details>

**Comment by michaelweinold** [comment]
...weird, especially since `psutil` has been removed from the dependency tree of `bw2io` with https://github.com/brightway-lca/brightway-hub/issues/7#issuecomment-1597381048.

**Comment by cmutel** [comment]
Maybe some invalid cache got cleared? Not sure how that could even be remotely possible, but any sufficiently advanced technology is indistinguishable from magic, as they say.

**Comment by michaelweinold** [comment]
Great, @cmutel broke it again - thanks, @cmutel! 😜

**Comment by michaelweinold** [comment]
Dependency tree investigation:

#### PyPI Wheel (via [`johnnydep`](https://github.com/wimglenn/johnnydep)):

```bash
johnnydep bw2io==0.9.dev21
```

<details>
  <summary>Full Dependency Tree</summary>

  ```
  bw2io==0.9.dev21                               Tools for importing and export life cycle inventory databases
  ├── bw-migrations                              Migration data and utilities for Brightway IO and LCA in general
  │   ├── bw2data                                Tools for the management of inventory databases and impact assessment methods. Part of the Brightway2 LCA Framework
  │   │   ├── appdirs                            A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  │   │   ├── bw2parameters                      Contains all the python boilerplate you need to create a Brightway ecosystem package.
  │   │   │   ├── asteval                        Safe, minimalistic evaluator of python expression using ast module
  │   │   │   ├── astunparse                     An AST unparser for Python
  │   │   │   │   ├── six<2.0,>=1.6.1            Python 2 and 3 compatibility utilities
  │   │   │   │   └── wheel<1.0,>=0.23.0         A built-package format for Python
  │   │   │   ├── numpy                          Fundamental package for array computing in Python
  │   │   │   ├── pint                           Physical quantities module
  │   │   │   │   └── typing-extensions          Backported and Experimental Type Hints for Python 3.7+
  │   │   │   └── stats-arrays                   Standard NumPy array interface for defining uncertain parameters
  │   │   │       ├── numpy                      Fundamental package for array computing in Python
  │   │   │       └── scipy                      Fundamental algorithms for scientific computing in Python
  │   │   │           └── numpy<1.28.0,>=1.21.6  Fundamental package for array computing in Python
  │   │   ├── docopt                             Pythonic argument parser, that will make you smile
  │   │   ├── eight                              Python 2 to the power of 3. A lightweight porting helper library.
  │   │   │   └── future<0.19,>=0.16             Clean single-source support for Python 3 and 2
  │   │   ├── fasteners                          A python package that provides useful locks
  │   │   ├── future                             Clean single-source support for Python 3 and 2
  │   │   ├── lxml                               Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
  │   │   ├── numpy                              Fundamental package for array computing in Python
  │   │   ├── peewee>=3.9.4                      a little orm
  │   │   ├── psutil                             Cross-platform lib for process and system monitoring in Python.
  │   │   ├── pyprind                            Python Progress Bar and Percent Indicator Utility
  │   │   ├── requests>=1.1.0                    Python HTTP for Humans.
  │   │   │   ├── certifi>=2017.4.17             Python package for providing Mozilla's CA Bundle.
  │   │   │   ├── charset-normalizer<4,>=2       The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  │   │   │   ├── idna<4,>=2.5                   Internationalized Domain Names in Applications (IDNA)
  │   │   │   └── urllib3<3,>=1.21.1             HTTP library with thread-safe connection pooling, file post, and more.
  │   │   ├── scipy                              Fundamental algorithms for scientific computing in Python
  │   │   │   └── numpy<1.28.0,>=1.21.6          Fundamental package for array computing in Python
  │   │   ├── stats-arrays                       Standard NumPy array interface for defining uncertain parameters
  │   │   │   ├── numpy                          Fundamental package for array computing in Python
  │   │   │   └── scipy                          Fundamental algorithms for scientific computing in Python
  │   │   │       └── numpy<1.28.0,>=1.21.6      Fundamental package for array computing in Python
  │   │   ├── unicodecsv                         Python2's stdlib csv module is nice, but it doesn't support unicode. This module is a drop-in replacement which *does*.
  │   │   ├── voluptuous                         UNKNOWN
  │   │   ├── whoosh                             Fast, pure-Python full text indexing, search, and spell checking library.
  │   │   └── wrapt                              Module for decorators, wrappers and monkey patching.
  │   ├── pandas                                 Powerful data structures for data analysis, time series, and statistics
  │   │   ├── numpy>=1.22.4                      Fundamental package for array computing in Python
  │   │   ├── python-dateutil>=2.8.2             Extensions to the standard Python datetime module
  │   │   │   └── six>=1.5                       Python 2 and 3 compatibility utilities
  │   │   ├── pytz>=2020.1                       World timezone definitions, modern and historical
  │   │   └── tzdata>=2022.1                     Provider of IANA time zone data
  │   └── stats-arrays                           Standard NumPy array interface for defining uncertain parameters
  │       ├── numpy                              Fundamental package for array computing in Python
  │       └── scipy                              Fundamental algorithms for scientific computing in Python
  │           └── numpy<1.28.0,>=1.21.6          Fundamental package for array computing in Python
  ├── bw-processing                              Tools to create structured arrays in a common format
  │   ├── fs                                     Python's filesystem abstraction layer
  │   │   ├── appdirs~=1.4.3                     A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  │   │   ├── setuptools                         Easily download, build, install, upgrade, and uninstall Python packages
  │   │   └── six~=1.10                          Python 2 and 3 compatibility utilities
  │   ├── numpy                                  Fundamental package for array computing in Python
  │   └── pandas                                 Powerful data structures for data analysis, time series, and statistics
  │       ├── numpy>=1.22.4                      Fundamental package for array computing in Python
  │       ├── python-dateutil>=2.8.2             Extensions to the standard Python datetime module
  │       │   └── six>=1.5                       Python 2 and 3 compatibility utilities
  │       ├── pytz>=2020.1                       World timezone definitions, modern and historical
  │       └── tzdata>=2022.1                     Provider of IANA time zone data
  ├── bw2calc>=1.7.4
  │   ├── eight                                  Python 2 to the power of 3. A lightweight porting helper library.
  │   │   └── future<0.19,>=0.16                 Clean single-source support for Python 3 and 2
  │   ├── numpy                                  Fundamental package for array computing in Python
  │   ├── scipy                                  Fundamental algorithms for scientific computing in Python
  │   │   └── numpy<1.28.0,>=1.21.6              Fundamental package for array computing in Python
  │   └── stats-arrays                           Standard NumPy array interface for defining uncertain parameters
  │       ├── numpy                              Fundamental package for array computing in Python
  │       └── scipy                              Fundamental algorithms for scientific computing in Python
  │           └── numpy<1.28.0,>=1.21.6          Fundamental package for array computing in Python
  ├── bw2data>=3.5.1                             Tools for the management of inventory databases and impact assessment methods. Part of the Brightway2 LCA Framework
  │   ├── appdirs                                A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
  │   ├── bw2parameters                          Contains all the python boilerplate you need to create a Brightway ecosystem package.
  │   │   ├── asteval                            Safe, minimalistic evaluator of python expression using ast module
  │   │   ├── astunparse                         An AST unparser for Python
  │   │   │   ├── six<2.0,>=1.6.1                Python 2 and 3 compatibility utilities
  │   │   │   └── wheel<1.0,>=0.23.0             A built-package format for Python
  │   │   ├── numpy                              Fundamental package for array computing in Python
  │   │   ├── pint                               Physical quantities module
  │   │   │   └── typing-extensions              Backported and Experimental Type Hints for Python 3.7+
  │   │   └── stats-arrays                       Standard NumPy array interface for defining uncertain parameters
  │   │       ├── numpy                          Fundamental package for array computing in Python
  │   │       └── scipy                          Fundamental algorithms for scientific computing in Python
  │   │           └── numpy<1.28.0,>=1.21.6      Fundamental package for array computing in Python
  │   ├── docopt                                 Pythonic argument parser, that will make you smile
  │   ├── eight                                  Python 2 to the power of 3. A lightweight porting helper library.
  │   │   └── future<0.19,>=0.16                 Clean single-source support for Python 3 and 2
  │   ├── fasteners                              A python package that provides useful locks
  │   ├── future                                 Clean single-source support for Python 3 and 2
  │   ├── lxml                                   Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
  │   ├── numpy                                  Fundamental package for array computing in Python
  │   ├── peewee>=3.9.4                          a little orm
  │   ├── psutil                                 Cross-platform lib for process and system monitoring in Python.
  │   ├── pyprind                                Python Progress Bar and Percent Indicator Utility
  │   ├── requests>=1.1.0                        Python HTTP for Humans.
  │   │   ├── certifi>=2017.4.17                 Python package for providing Mozilla's CA Bundle.
  │   │   ├── charset-normalizer<4,>=2           The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  │   │   ├── idna<4,>=2.5                       Internationalized Domain Names in Applications (IDNA)
  │   │   └── urllib3<3,>=1.21.1                 HTTP library with thread-safe connection pooling, file post, and more.
  │   ├── scipy                                  Fundamental algorithms for scientific computing in Python
  │   │   └── numpy<1.28.0,>=1.21.6              Fundamental package for array computing in Python
  │   ├── stats-arrays                           Standard NumPy array interface for defining uncertain parameters
  │   │   ├── numpy                              Fundamental package for array computing in Python
  │   │   └── scipy                              Fundamental algorithms for scientific computing in Python
  │   │       └── numpy<1.28.0,>=1.21.6          Fundamental package for array computing in Python
  │   ├── unicodecsv                             Python2's stdlib csv module is nice, but it doesn't support unicode. This module is a drop-in replacement which *does*.
  │   ├── voluptuous                             UNKNOWN
  │   ├── whoosh                                 Fast, pure-Python full text indexing, search, and spell checking library.
  │   └── wrapt                                  Module for decorators, wrappers and monkey patching.
  ├── bw2parameters>=0.7.1                       Contains all the python boilerplate you need to create a Brightway ecosystem package.
  │   ├── asteval                                Safe, minimalistic evaluator of python expression using ast module
  │   ├── astunparse                             An AST unparser for Python
  │   │   ├── six<2.0,>=1.6.1                    Python 2 and 3 compatibility utilities
  │   │   └── wheel<1.0,>=0.23.0                 A built-package format for Python
  │   ├── numpy                                  Fundamental package for array computing in Python
  │   ├── pint                                   Physical quantities module
  │   │   └── typing-extensions                  Backported and Experimental Type Hints for Python 3.7+
  │   └── stats-arrays                           Standard NumPy array interface for defining uncertain parameters
  │       ├── numpy                              Fundamental package for array computing in Python
  │       └── scipy                              Fundamental algorithms for scientific computing in Python
  │           └── numpy<1.28.0,>=1.21.6          Fundamental package for array computing in Python
  ├── lxml                                       Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
  ├── mrio-common-metadata                       Common Datapackage schema and utilities for MRIO tables
  │   ├── openpyxl                               A Python library to read/write Excel 2010 xlsx/xlsm files
  │   │   └── et-xmlfile                         An implementation of lxml.xmlfile for the standard library
  │   ├── pandas                                 Powerful data structures for data analysis, time series, and statistics
  │   │   ├── numpy>=1.22.4                      Fundamental package for array computing in Python
  │   │   ├── python-dateutil>=2.8.2             Extensions to the standard Python datetime module
  │   │   │   └── six>=1.5                       Python 2 and 3 compatibility utilities
  │   │   ├── pytz>=2020.1                       World timezone definitions, modern and historical
  │   │   └── tzdata>=2022.1                     Provider of IANA time zone data
  │   ├── pyxlsb                                 Excel 2007-2010 Binary Workbook (xlsb) parser
  │   ├── scipy                                  Fundamental algorithms for scientific computing in Python
  │   │   └── numpy<1.28.0,>=1.21.6              Fundamental package for array computing in Python
  │   └── xlrd                                   Library for developers to extract data from Microsoft Excel (tm) .xls spreadsheet files
  ├── numpy                                      Fundamental package for array computing in Python
  ├── openpyxl                                   A Python library to read/write Excel 2010 xlsx/xlsm files
  │   └── et-xmlfile                             An implementation of lxml.xmlfile for the standard library
  ├── platformdirs                               A small Python package for determining appropriate platform-specific dirs, e.g. a "user data dir".
  ├── requests                                   Python HTTP for Humans.
  │   ├── certifi>=2017.4.17                     Python package for providing Mozilla's CA Bundle.
  │   ├── charset-normalizer<4,>=2               The Real First Universal Charset Detector. Open, modern and actively maintained alternative to Chardet.
  │   ├── idna<4,>=2.5                           Internationalized Domain Names in Applications (IDNA)
  │   └── urllib3<3,>=1.21.1                     HTTP library with thread-safe connection pooling, file post, and more.
  ├── scipy                                      Fundamental algorithms for scientific computing in Python
  │   └── numpy<1.28.0,>=1.21.6                  Fundamental package for array computing in Python
  ├── stats-arrays                               Standard NumPy array interface for defining uncertain parameters
  │   ├── numpy                                  Fundamental package for array computing in Python
  │   └── scipy                                  Fundamental algorithms for scientific computing in Python
  │       └── numpy<1.28.0,>=1.21.6              Fundamental package for array computing in Python
  ├── tqdm                                       Fast, Extensible Progress Meter
  ├── unidecode                                  ASCII transliterations of Unicode text
  ├── voluptuous                                 UNKNOWN
  ├── xlrd                                       Library for developers to extract data from Microsoft Excel (tm) .xls spreadsheet files
  └── xlsxwriter                                 A Python module for creating Excel XLSX files.
  ```
<\details>

**Comment by michaelweinold** [comment]
...the tree branches like this to the forbidden packages:

```bw2io==0.9.dev21 > bw-migrations > bw2data > unicodecsv```

```bw2io==0.9.dev21 > bw2data>=3.5.1 > psutil```

```bw2io==0.9.dev21 > bw_migrations > bw2data > docopt```

**Comment by cmutel** [comment]
OK, see if bw2io `0.9.dev22` treats you any better.

Edit: Yep, seems good now!
